version: "3.9"
services:
  nodejs:
    build:
      context: ./nodejs
    image: headstarter-nodejs-comp
    depends_on:
      - mysql
    env_file:
      - ./NodeJS/nodejs.env
    ports:
      - "30001:3000"
    container_name: headstarter-nodejs-comp
  mysql:
    build:
      context: ./mysql
    image: headstarter-mysql-comp
    env_file:
      - ./MySQL/mysql.env
    volumes:
      - headstartdata:/var/lib/mysql
    container_name: headstarter-mysql-comp
volumes:
  headstartdata: